---
services:
  monitoring:
    image: louislam/uptime-kuma:1.23.16
    container_name: uptime-kuma
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
    security_opt:
      - no-new-privileges:true
    network_mode: host
    volumes:
      - ./docker-compose.d/data:/app/data:rw
