---
services:
  jellyfin:
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`monitoring.leberkaslabs.de`)
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.services.jellyfin.loadBalancer.server.port=3001
    networks:
      - traefik

networks:
  traefik:
    name: traefik
