---
services:
  monitoring:
    labels:
      - traefik.enable=true
      - traefik.http.routers.monitoring.entrypoints=websecure
      - traefik.http.routers.monitoring.rule=Host(`monitoring.leberkaslabs.de`)
      - traefik.http.routers.monitoring.tls=true
      - traefik.http.services.monitoring.loadBalancer.server.port=3001
    networks:
      - traefik

networks:
  traefik:
    name: traefik
